# Generated by Django 5.1.2 on 2024-10-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('est_date', models.PositiveBigIntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('overview', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('services', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
