# Generated by Django 5.1.2 on 2024-10-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_additional_info_resume_address_resume_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
    ]
