# Generated by Django 5.1.2 on 2024-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_remove_resume_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='state',
            field=models.CharField(choices=[('Province one', 'Province one'), ('Province two', 'Province two'), ('Bagmati', 'Bagmati'), ('Gandaki', 'Gandaki'), ('Lumbini', 'Lumbini'), ('Karnali', 'Karnali'), ('Sudurpashchim', 'Sudurpashchim')], max_length=50),
        ),
    ]
