# Generated by Django 5.1.2 on 2024-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_time',
            new_name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
