# Generated by Django 5.1.2 on 2024-10-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images/%y/%m/&=%d'),
        ),
    ]
