# Generated by Django 5.1.2 on 2024-10-18 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_job_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uploaded_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
