# Generated by Django 5.1.2 on 2024-10-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_uploaded_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.IntegerField(max_length=20),
        ),
    ]
