# Generated by Django 5.1.2 on 2024-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
